ALTER TABLE journeys ADD COLUMN IF NOT EXISTS pickup_pin VARCHAR(16);
ALTER TABLE journeys ADD COLUMN IF NOT EXISTS pickup_pin_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE journeys ADD COLUMN IF NOT EXISTS pickup_pin_failed_attempts INTEGER DEFAULT 0;
ALTER TABLE journeys ADD COLUMN IF NOT EXISTS pickup_pin_locked_until TIMESTAMPTZ;
